### ISSUE TITLE
Unable to connect to printer Error on Sunmi  V2s Plus Printer

### ISSUE THREAD

**Issue by vineethamanoj12** [uvesshaikh/SunmiPrinter#1]
Hi,
Thank you for sharing the library. We are currently working on printing from a .NET MAUI application to a Sunmi V2s Plus printer, but encountering the error "Unable to connect to printer". When using the same code to print from a Sunmi V2 PRO device, it functions correctly. We have followed the instructions provided in the repository https://github.com/uvesshaikh22/SunmiPrinter  on GitHub. Could you please suggest a solution to resolve this issue.

Thanks.

**Comment by vineethamanoj12** [comment]
As we resolved the issue.
For V2s and V2s Plus models, due to the requirements of Android version, you need to add package visibility declaration
before connecting to the service, and add the following commands in AndroidManifest.xml:
<queries>
	<package android:name="woyou.aidlservice.jiuiv5"/>
</queries>

**Comment by vineethamanoj12** [comment]
Resolved..
For V2s and V2s Plus models, due to the requirements of Android version, you need to add package visibility declaration
before connecting to the service, and add the following commands in AndroidManifest.xml:
`<queries>
<package android:name=“woyou.aidlservice.jiuiv5”/>
</queries>
`

**Comment by nbulfon** [comment]
Thanks!!. You resolved an error that we have for a lot of time with the Sunmi V2s.
